---
version: 2.1
executors:
  builder:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          TERM: xterm
jobs:
  build:
    executor: builder
    working_directory: ~/poc-spring-boot
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}-{{ checksum "./project/build.properties" }}-{{ checksum "./project/plugins.sbt" }}-{{ checksum "./project/Dependencies.scala" }}
      - run:
          name: Check that everything is formatted properly
          command: ./sbt scalafmtSbtCheck scalafmtCheckAll
      - run:
          name: Run clean coverage test
          command: ./sbt clean coverage test
      - run:
          name: Run coverage report
          command: ./sbt coverageReport
      - run:
          name: Run codacy coverage
          command: ./sbt codacyCoverage
      - run:
          name: Run stage
          command: ./sbt stage
      - save_cache:
          paths:
            - ../.m2
            - ../.ivy2/cache
            - ../.sbt/boot/
            - ../.sbt/launchers
          key: v1-dependencies-{{ checksum "build.sbt" }}-{{ checksum "./project/build.properties" }}-{{ checksum "./project/plugins.sbt" }}-{{ checksum "./project/Dependencies.scala" }}
      - persist_to_workspace:
          root: .
          paths:
            - ./target/universal/stage
workflows:
  version: 2
  poc-spring-boot:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/